config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :links, only: [:new, :create, :update, :destroy]
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, :url => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_secure_password
  validates :email, presence: true,
                    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user || User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    if current_user
      @user = current_user
    else
      redirect_to login_path
    end
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
    else
      flash[:error] = "Invalid link"
    end
    redirect_to root_path
  end

  private
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password_confirmation])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login Invalid"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="ui container">
  <div class="well">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/links/index.html.erb
<h4>Welcome, <%= @user.email %></h4> <%= link_to "Sign Out", logout_path, method: :delete %>
<br><br>

<% if flash[:error].present? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash[:error] %>
  </div>
<% end %>

<div class="jumbotron" id="create-link">
  <h2>Create Link</h2>
  <%= bootstrap_form_for :link, :url => links_path  do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :url %>
    <%= f.submit "Create" %>
  <% end %>
  <br>

  <div class="centered well">
    <h2>Links</h2>
    <% @user.links.each do |link| %>
      <div class="well">
        <%= link.title %>: <%= link.url %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= bootstrap_form_for(User.new) do |f| %>
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create Account" %>
<% end %>